// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqebsICmat2GjP50kw0MOh5ho8MHnWjfo',
    appId: '1:634922503859:web:5c3abd65495160daf92ac6',
    messagingSenderId: '634922503859',
    projectId: 'fb-virtual-marketplace-app',
    authDomain: 'fb-virtual-marketplace-app.firebaseapp.com',
    storageBucket: 'fb-virtual-marketplace-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_t2UNs4LTeQHaEkhwpAaGcjaSseemN3c',
    appId: '1:634922503859:android:ce245e3dcb3fece9f92ac6',
    messagingSenderId: '634922503859',
    projectId: 'fb-virtual-marketplace-app',
    storageBucket: 'fb-virtual-marketplace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQk3kLrCDZ41s7E8omBaYNEHqD6z3dkE',
    appId: '1:634922503859:ios:03a68fadc7c0b8e1f92ac6',
    messagingSenderId: '634922503859',
    projectId: 'fb-virtual-marketplace-app',
    storageBucket: 'fb-virtual-marketplace-app.firebasestorage.app',
    iosBundleId: 'com.example.virtualMarketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxQk3kLrCDZ41s7E8omBaYNEHqD6z3dkE',
    appId: '1:634922503859:ios:03a68fadc7c0b8e1f92ac6',
    messagingSenderId: '634922503859',
    projectId: 'fb-virtual-marketplace-app',
    storageBucket: 'fb-virtual-marketplace-app.firebasestorage.app',
    iosBundleId: 'com.example.virtualMarketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqebsICmat2GjP50kw0MOh5ho8MHnWjfo',
    appId: '1:634922503859:web:7188c8f8a4cb9242f92ac6',
    messagingSenderId: '634922503859',
    projectId: 'fb-virtual-marketplace-app',
    authDomain: 'fb-virtual-marketplace-app.firebaseapp.com',
    storageBucket: 'fb-virtual-marketplace-app.firebasestorage.app',
  );
}
